#!/bin/sh
set -e

/usr/bin/xattr -dr com.apple.quarantine "/Applications/GoldSun.app" 2>/dev/null || true
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f "/Applications/GoldSun.app" 2>/dev/null || true
exit 0
